"""postgres baseline: full schema from SQLModel metadata

PG 谱系的第一个 revision:在全新 PostgreSQL 上一次性建出全部业务表。
这同时补上了 MySQL 时代「0001 基线为空、表结构全靠 create_all」的历史 TODO
(旧谱系归档在 alembic/legacy_mysql/)。

pgvector 扩展也在此启用(IF NOT EXISTS 保证幂等):
- 镜像是 pgvector/pgvector:pg18,扩展文件已预装,这里只做注册
- 需要 superuser/owner 权限——本地 compose 的 POSTGRES_USER 即超级用户;
  未来上云时若应用账号权限不足,由初始化脚本单独执行
- 一期只启用扩展不建向量表:向量维度是 DDL 常量,取决于二期 embedding 模型选型

Revision ID: cf50d924c9f7
Revises:
Create Date: 2026-09-02 16:48:42.239601
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 —— 列类型引用了 sqlmodel.sql.sqltypes.AutoString


revision: str = 'cf50d924c9f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector 向量扩展(幂等):向量表二期接入时依赖它
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_paths',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('emoji', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('accent', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('current_jobs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('emoji', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('industries',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('emoji', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('accent', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('overview', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('key_points', sa.JSON(), nullable=False),
    sa.Column('links', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('emoji', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('tagline', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('accent', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_role'), 'chat_messages', ['role'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('qtype', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('answer_indices', sa.JSON(), nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_content_hash'), 'questions', ['content_hash'], unique=True)
    op.create_index(op.f('ix_questions_job_id'), 'questions', ['job_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_deleted_at'), 'tasks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index('ix_tasks_user_deleted_status_created', 'tasks', ['user_id', 'deleted_at', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('task_operation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('from_status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('to_status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_task_operation_user_key')
    )
    op.create_index(op.f('ix_task_operation_records_created_at'), 'task_operation_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_operation_records_idempotency_key'), 'task_operation_records', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_task_operation_records_task_id'), 'task_operation_records', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_operation_records_user_id'), 'task_operation_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_operation_records_user_id'), table_name='task_operation_records')
    op.drop_index(op.f('ix_task_operation_records_task_id'), table_name='task_operation_records')
    op.drop_index(op.f('ix_task_operation_records_idempotency_key'), table_name='task_operation_records')
    op.drop_index(op.f('ix_task_operation_records_created_at'), table_name='task_operation_records')
    op.drop_table('task_operation_records')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index('ix_tasks_user_deleted_status_created', table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deleted_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_questions_job_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_content_hash'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_role'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_table('jobs')
    op.drop_table('industries')
    op.drop_table('current_jobs')
    op.drop_table('career_paths')
    # ### end Alembic commands ###
